title: Personal Hompage
description: My Personal Hompage for resume, portfolio
author: Jihwan Min
github: https://github.com/rluver
about: 비정형 데이터를 활용한 이상 탐지 및 예측에 관심 갖고 있는 엔지니어 민지환입니다.
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y

enableTags: true
tagarray: []

collections:
  project:
    output: true
    permalink: /project/:path/

social:
    - icon: fa-notion
      link: "https://pinnate-orchid-cc0.notion.site/112b5be9c19b4cfea831dc1048523673"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "https://www.linkedin.com/in/%EC%A7%80%ED%99%98-%EB%AF%BC-65a384204/"
    - icon: fa-github
      link: "https://github.com/agusmakmun"

share:
  twitter_username: github.io
  fb_appid: 1749788565247320

urls:
    - text: About Me
      url: /about/
    - text: My Projects
      url: /projects/
    - text: Portfolio
      link: "https://pinnate-orchid-cc0.notion.site/Portfolio-06915ea99e3a44bcaa6573e0bef175cb"

url: "https://rluver.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
